// Define the expected return structure from an executor's execute method
// This should be consistent with TaskExecutionResult, but perhaps slightly simpler before serialization
export interface ExecutorResult {
  nextNodeIds: string[]; // Or whatever type is used for next node IDs
  logs?: string[]; // Optional logs generated by the executor
  error?: string; // Optional error message if execution failed within the executor
  // Any other results the orchestrator needs (e.g., a specific return value for decisions)
  returnValue?: any; // For decision nodes, script results etc.
}
