version: "3.9"

services:
  caidense-synth-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    # env_file:
    #   - ./docker-var.env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - caidense_network

volumes:
  frontend_data:

networks:
  caidense_network:
    name: caidense-network
    external: true
